data=read.table(file = 'hw1_data.csv',sep=',',header=T)
names(data)
head(data)
tail(data)
dim(data)
sum(is.na(data$Ozone))
mean(data$Ozone,na.rm=T)
mean(data$Solar.R[data$Ozone>31 & data$Temp>90],na.rm=T)
mean(data$Temp[data$Month==6],na.rm=T)
max(data$Ozone[data$Month==5],na.rm=T)
